### PR TITLE
Adding more container sizes

### PR DESCRIPTION
**Pull request by iamgnat**
Added the following container sizes to round things out:

* 1x3
* 1x4
* 1x5
* 2x3
* 2x4
* 2x5
* 3x2
* 3x3
* 3x4
* 3x5
* 4x3
* 4x4
* 4x5

### CODE REVIEW

**Comment by iamgnat** [comment]
Note: I have printed all the 1x and 2x containers to verify the fit. I'm printing the 3x containers now and will do the 4x ones tomorrow morning, but I am confident that they will also fit based on the 1s and 2s.

**Comment by iamgnat** [comment]
The 3s and 4s have now been tested and appear to fit well.

**Comment by ProjectsWithRed** [comment]
@iamgnat You should have just asked for those sizes! Because I can very easily and quickly add them and ensure 100% correct fit. Although I really appreciate the work you have done, I would rather create the sizes with the template I have to ensure full consistency for all sizes and models.

I will add the sizes shortly. However, there are some sizes that are not practical, such as:
- `4x5`, this does not make any sense, since you can just use the drawer without any containers for this size.
- `1x5`, a `4x1` can be used instead. You will have more space using the `4x1`.
- `2x5`, again, a `4x2` could be used.
- `3x4`, `3x5`, `4x3`, `4x4`, these are all too big, if you need that size container to store an item in the drawer, then that item should not be organised inside the relatively small drawer.

Thank you for the help!

Just out of curiosity, how were you creating the different sizes without the model files?

**Comment by ProjectsWithRed** [comment]
I just added sizes `1x3`, `1x4`, `2x3`, `2x4`, `3x2`, `3x3` 👍.

**Comment by iamgnat** [comment]
> 4x5, this does not make any sense, since you can just use the drawer without any containers for this size.

I initially thought that, but then I tossed some bearings into one of my inserts that were greasier than I expected. By having the 4x5 insert I can just replace the insert rather than the whole drawer (probably minimal difference in print time and material unless you want to repurpose the drawer with smaller bins). Additionally using the 4x5 insert allows you to carry the same color through to match your other drawers if such is important.

> 1x5, a 4x1 can be used instead. You will have more space using the 4x1.

That substitution only works if the other inserts in that drawer that allow for the 4x1 to fit. Additionally 4 1x5s may be more preferable for some situations (e.g. only have to pull the drawer part way out to see and access all the items).

> 2x5, again, a 4x2 could be used.

Again it all depends on what other inserts you are using on if that is practical or not.

> 3x4, 3x5, 4x3, 4x4, these are all too big, if you need that size container to store an item in the drawer.

I disagree. Here are some examples of those sizes with items in them: https://photos.app.goo.gl/j8L4aQ9EQR2Me1z49

If another insert was in the same drawer with those loose in the drawer itself and I removed that insert (e.g. take just the insert with it's parts rather than the whole drawer), reinstalling the insert would be complicated by having to keep the loose parts out of the way. Additionally, as with the 4x5, it allows for a consistent color scheme if that is important.

> Just out of curiosity, how were you creating the different sizes without the model files?

I chopped up a drawer of each size into 2 ends and a middle and then scaled the middle to be the correct length. This was easy for everything except the x5s as a direct multiplication of the length of the x1 gave me the correct target length. Turns out the x5 length isn't 5 times the length of the x1 and I had to shave an extra 0.5mm out for it to fit.

If you could add the models to the project (especially if they are parametric) that would be great as it would allow people it customize things specific to their needs (e.g. longer/thinner drawers, taller drawers, more than 9 drawers, etc..).

I see you already added most of the inserts. If you could add the larger ones too (3x4, 3x5, 4x3, 4x4, and 4x5) that would be awesome.

Thanks.

**Comment by ProjectsWithRed** [comment]
Since you are insisting of course I will add them! Again, thank you for the time you have spent with this.

Sizes `3x4`, `3x5`, `4x3`, `4x4`, and `4x5` are all added now.

**Comment by iamgnat** [comment]
Thanks. Looks like 1x5 and 2x5 are missing to round out the set (forgot them in my "please add" list).

**Pull request closed without merging**
